# Generated by Django 2.1.7 on 2020-02-10 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200209_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('qaDataset', 'create qa dataset')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='qadatasetannotation',
            unique_together={('document', 'user', 'id', 'question', 'answer', 'start_answer', 'end_answer')},
        ),
    ]
