# Generated by Django 2.1.7 on 2020-04-01 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200210_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentannotation',
            name='text',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='documentannotation',
            unique_together={('document', 'user', 'label', 'text')},
        ),
    ]
