# Generated by Django 2.1.7 on 2020-04-01 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200401_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentannotation',
            old_name='text',
            new_name='annotation_text',
        ),
        migrations.AlterUniqueTogether(
            name='documentannotation',
            unique_together={('document', 'user', 'label', 'annotation_text')},
        ),
    ]
