# Generated by Django 2.1.7 on 2020-04-01 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200401_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceannotation',
            name='annotation_text',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='sequenceannotation',
            unique_together={('document', 'user', 'label', 'start_offset', 'end_offset', 'annotation_text')},
        ),
    ]
