# Generated by Django 2.1.7 on 2020-04-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200420_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seq2seqannotation',
            name='label',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Label'),
        ),
    ]
