# Generated by Django 2.1.7 on 2020-04-20 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20200420_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='seq2seqannotation',
            name='sentence',
            field=models.CharField(default='none', max_length=5000),
        ),
        migrations.AddField(
            model_name='seq2seqannotation',
            name='text',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.RemoveField(
            model_name='seq2seqannotation',
            name='annotation_text',
        ),
        migrations.RemoveField(
            model_name='seq2seqannotation',
            name='label',
        ),
        migrations.AlterUniqueTogether(
            name='seq2seqannotation',
            unique_together={('document', 'user', 'text', 'sentence')},
        ),
    ]
